Repository TeamBeMyPlan/BeMyPlan-Server-Release, pull requests merged in 2022-06, with the labels that each got.

#86 [#85] 여행일정 조회시 userId 쿼리스트링 파라미터 추가 및 로그인/회원가입 시 닉네임 반환 추가
  src/main/java/com/deploy/bemyplan/controller/auth/AuthController.java
  src/main/java/com/deploy/bemyplan/controller/auth/dto/response/LoginResponse.java
  src/main/java/com/deploy/bemyplan/controller/plan/PlanRetrieveController.java
  src/main/java/com/deploy/bemyplan/controller/plan/dto/request/RetrievePlansRequest.java
  src/main/java/com/deploy/bemyplan/domain/plan/repository/PlanRepositoryCustom.java
  src/main/java/com/deploy/bemyplan/domain/plan/repository/PlanRepositoryCustomImpl.java
  src/main/java/com/deploy/bemyplan/service/plan/PlanRetrieveService.java
  src/main/java/com/deploy/bemyplan/service/user/UserService.java
Labels: bug, 🐱제준

#90 [CHORE] CodeDeploy + Nginx 배포 설정
  appspec.yml
  scripts/deploy.sh
  scripts/health_check.sh
  scripts/run_new_was.sh
  scripts/switch.sh
  src/main/java/com/deploy/bemyplan/controller/log/LoggingController.java
Labels: deploy

#93 [#92] test:nginx 무중단 배포 테스트
  appspec.yml
Labels: bug
