Repository TeamBeMyPlan/BeMyPlan-Server-Release, pull requests merged in 2022-05, with the labels that each got.

#62 [fix] domain TravelTheme theme 값 추가 및 RegionType thumbnailURL 추가
  src/main/java/com/deploy/bemyplan/domain/plan/RegionType.java
  src/main/java/com/deploy/bemyplan/domain/plan/TravelTheme.java
Labels: domain

#64 [#63] domain plan entity price 추가
  src/main/java/com/deploy/bemyplan/domain/plan/Plan.java
Labels: domain, 🐱제준

#66 [#65] booleanExpression eqUserId
  src/main/java/com/deploy/bemyplan/domain/order/repository/OrderRepositoryCustomImpl.java
  src/main/java/com/deploy/bemyplan/domain/scrap/repository/ScrapRepositoryCustomImpl.java
Labels: enhancement

#67 [#65] booleanExpression eqUserId 적용
  src/main/java/com/deploy/bemyplan/domain/scrap/repository/ScrapRepositoryCustomImpl.java
Labels: enhancement

#69 [#65] booleanExpression inPlanIds
  src/main/java/com/deploy/bemyplan/domain/order/repository/OrderRepositoryCustomImpl.java
  src/main/java/com/deploy/bemyplan/domain/scrap/repository/ScrapRepositoryCustomImpl.java
Labels: enhancement

#70 [#65] booleanExpression Objects.isNull() 사용
  src/main/java/com/deploy/bemyplan/domain/order/repository/OrderRepositoryCustomImpl.java
  src/main/java/com/deploy/bemyplan/domain/plan/repository/PlanRepositoryCustomImpl.java
  src/main/java/com/deploy/bemyplan/domain/scrap/repository/ScrapRepositoryCustomImpl.java
Labels: enhancement

#73 fix: SpotCategory enum value 추가
  src/main/java/com/deploy/bemyplan/domain/plan/SpotCategoryType.java
Labels: bug, domain, 🐱제준

#74 [#65] 정렬 기준 수정
  src/main/java/com/deploy/bemyplan/domain/plan/repository/PlanRepositoryCustomImpl.java
Labels: fix

#77 fix: SpotCategory category enum value 수정
  src/main/java/com/deploy/bemyplan/domain/plan/SpotCategoryType.java
Labels: bug, domain, 🐱제준

#79 [#78] 중복된 구매인지 체크하는 로직 구현
  src/main/java/com/deploy/bemyplan/common/exception/ErrorCode.java
  src/main/java/com/deploy/bemyplan/domain/order/repository/OrderRepositoryCustom.java
  src/main/java/com/deploy/bemyplan/domain/order/repository/OrderRepositoryCustomImpl.java
  src/main/java/com/deploy/bemyplan/service/order/OrderService.java
Labels: bug, order, 🐱제준

#83 fix: 미리보기 nickname도 넘겨주기
  src/main/java/com/deploy/bemyplan/service/plan/PlanRetrieveService.java
  src/main/java/com/deploy/bemyplan/service/plan/dto/response/PlanPreviewInfoResponse.java
  src/main/java/com/deploy/bemyplan/service/plan/dto/response/PlanPreviewResponse.java
Labels: bug, 🐱제준
